CommitMsg:
  CapitalizedSubject:
    enabled: false

  EmptyMessage:
    enabled: false

  TrailingPeriod:
    enabled: true

  TextWidth:
    enabled: false

PreCommit:
  ALL:
    on_warn: fail

  AuthorEmail:
    enabled: true

  AuthorName:
    enabled: true

  MergeConflicts:
    enabled: true

  YamlSyntax:
    enabled: true

  BundleCheck:
    enabled: true

  Rspec:
    enabled: true
    command: [ 'bundle', 'exec', 'rspec' ] # Invoke within Bundler context

  RuboCop:
    enabled: false
    command: [ 'bundle', 'exec', 'rubocop' ] # Invoke within Bundler context

  RuboCopPerformance:
    enabled: true

  Fasterer:
    enabled: true

  BundleAudit:
    enabled: true

  Reek:
    enabled: true

  RailsSchemaUpToDate:
    enabled: false

  Prettier:
    enabled: true
    command: [ 'bundle', 'exec', 'rbprettier', '--write', '**/*.rb' ]

#  LolDba:
#    lol_dba db:find_indexes

PrePush:
  Brakeman:
    enabled: true
  Undercover:
    enabled: true
    required: true
    command: [ 'undercover', '--compare', 'main' ]
