require: rubocop-rspec

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/FeatureMethods:
  Exclude:
    - 'spec/features/**/*'
RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
