require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Capybara/FeatureMethods:
  Exclude:
    - 'spec/features/**/*'
RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
