language: ruby
cache: bundler
sudo: false
addons:
  chrome: stable
before_script:
- psql -c 'create database biblestudy_platform_test;' -U postgres
- gem install bundler
script: bundle exec rspec
before_install:
- "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu
  --remote-debugging-port=9222 http://localhost &"
- ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
- gem update bundler
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: af8e9a52-82fc-4627-9ece-d6c6d36b0986
  app: biblestudy-platform
  on:
    repo: andreheijstek/biblestudy_platform
  skip_cleanup: true
notifications:
  email:
  - andre.heijstek@gmail.com
