language: ruby
rvm: 2.3.0

before_script:
  - psql -c 'create database biblestudy_platform_test;' -U postgres

script: bundle exec rspec

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem update bundler
- wget https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
- mkdir geckodriver
- tar -xzf geckodriver-v0.14.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver

deploy:
  provider: heroku
  api_key:
    secure: wbSc7RTKvrRkobm2Bg41e4dnTpwct/pwQlWtQxizXtEj3hOXAUpy8eOWGdhAG8Q6Pvve4EKuinFK2pG0bzsTTWzEeI9khqvTITVbDQkAqMJeMMJHGqEse5MxmhaBT3lFDxFdiDQCklnuQp/S0pv2WSdqRWO53IE6gDldEBC0RHmulpb9o+UKAH+Ukb+pCBTeP5VzFfUAsRVYb253Ky81bLs09GDYep82m6hRX1bCcExP5tZCUwvRd9lMGfXxCmfmfIUyRiMUbiAvaZPcTM3ktecBJNo6Gngqfk/YDBmbnXWUJN7A4WvKlBnh+2Op9GSNpZW+dLGGcGHt1uEo2YhOZk2emoPEIOnYeX0JLjXdMJ4Kc/mkKuUH1NfuV/Wxl/la+/PLuVso53SbkbU72wpkV7yxiyVG5ixncr1W9pZWhnvoaiZp6ikLt9n6JjkYRWku/eY1mlqpScOU70CnqWi/s6+PjCeJGAYGdADU6OZ8GvwWu74LqUZ8yKIkpNJAiJlk4h3s94cwc23MvfdbaIwTrHwT5nbN9mqqF/TSZpP6W4zzwEy6Nb4P309OHKkbIhRbJEa4dwXHGghCKMvQqjgTy9VnOS6lBgp8/mIox3lzs2242jUiioKB5WPCdXLD2toFVAIax1MowXdar2ZUbdC38/uOD36iW+Ve5OD9kQYN1pM=
  app: biblestudy-platform, biblestudy-platform-acc
  on:
    repo: andreheijstek/biblestudy_platform

notifications:
  email:
    - andre.heijstek@improvementfocus.com

addons:
  - postgresql: "9.5.4"
  - firefox: "50.0"
