language: ruby
#rvm: 2.6.2 - is not needed, travis also uses the .ruby-version - so this removes a duplication
cache: bundler
sudo: false
addons:
  chrome: stable
before_script:
- psql -c 'create database biblestudy_platform_test;' -U postgres
- gem install bundler
script: bundle exec rspec
before_install:
- "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu
  --remote-debugging-port=9222 http://localhost &"
- ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
- gem update bundler
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: XBJdB0xf0MtdHMmqSSsRg25B1aOwsgSVUtS5h1wIkInd+yBaB9+nxE3jQYbefQ6cznFYODwgDvsOiqSv4ULkOLz+BWej+19PCijw7qOrPcwbCdSyzEgmTq9gWKk+6+N+EocD+QmzsNFk2szGSzmlhPVYxS95kNITQ+N514vvWPd4CyoBzpuDpmvHpTzX7ZNmaKVdj+xyYbiXmsGCIRTfYjl0tV+VU/LlajqZvcDo60EkHDL+AQcGQy1KI0rcQlXLiY4II8DYN2A2AnsHPvnubFzqjWev8Z41PpV/Mt6niY3R9Syf7e0Kmq8jTF4PvD/8P57MOnYxXWtBA9XEwAfWudGwnKW2IhRDKc72z7tUvhX6hDXDvM+DUeoo1nfj3tCGBfg4UiqcHBU+eI5yo2dBZSgoGPc9iD89/QGDjlaKPVaFsUGPyA7wo3GojTW4bcal/9+8I5hgFWHxRLbdsvLFoib2QOu6sm4yq1sKd6pDX0f0Ugok+seVCs0UgFg52Jo86wif6+GqiPgUx9A7SFF15MOlVsCn31J57zxWLrIy8nsKOzVRYuGPqLo1T51MQt9aFuEN5KiiGLTOwKYVavb/qvBv1RubAJzD+Lw3onUn7JUuvhkFE0aLiQsAasDIrxv+HqT442YciHx03LNJrQJLhOHgDUfyia2OF1km2ij/tJA=
  app: salty-headland-55387
  on:
    repo: andreheijstek/biblestudy_platform
notifications:
  email:
  - andre.heijstek@gmail.com
