language: ruby
cache: bundler
sudo: false
addons:
  chrome: stable
before_script:
- psql -c 'create database biblestudy_platform_test;' -U postgres
- gem install bundler
script: bundle exec rspec
before_install:
- "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu
  --remote-debugging-port=9222 http://localhost &"
- ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
- gem update bundler
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: JabysBpOx94E9ekafMSL3i8N+z8Q2D/QRfCmqqAbmDvtQH6rskCa5bZzxs7BwLbmzDORzsL19015NCBXNeLEc9QDZMtPwi35WJBfZVx1rwDMOm/m9jM87vw9IUy+KZniI4XM/KMjIF3bMXIeFLJ0AKBGrlsCnDkI4uHDRWidqZgHnpcUbGf+OZgxIoTOoCjgriEgxXQWYTKfC884FmbMa9KdKJXHU/97vLQtih/kERo/4hefn42W/qwWGy1cB6mdveSCOsXO/8ue4BAT1GYTdjatZyhcZvHblDVelyhGQpSxFx0LVqWpvbynPDhhFhSlX0RRztrXjXXHhGlqzzihI00CQJhn+qV/dp6jLNd+QjfKWSplu+MCXj0wgRkvKFIkDDe74tT4rM3j+qX6meHfFXLKSYIykzX3LXZ3HK7e46f8JrO80vac1iYiiDv0OOpKdv0Lux7AKXVKi4jX7Vic5P3eT7kPgeuFPLbhuWZBt0AEvybDUSDBX0ujB6HFhvyB2lHGZKimfH9NL/78c3/9e+9vWpVhj7yRQ+W8fQElIWrFuSltz9gu4rc2nmiSWnkuhcwz8e8DbvhLA1eyotWbCuJliQyQLOkiGMUykkRWizWPpwbY0HwsllKZkD+wEKRi0AbkMJG8TiE2BeK22v/7F5KkCTHbyAj+SsIEPlCUpoY=
  app: biblestudy-platform
  on:
    repo: andreheijstek/biblestudy_platform
notifications:
  email:
  - andre.heijstek@gmail.com
