databases:
  - name: biblestudy_platform_production
    databaseName: biblestudy_platform_production
    user: biblestudy_platform_production

services:
  - type: web
    name: biblestudy_platform_production
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: biblestudy_platform_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
