development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: andreheijstek
  password: Dwrzn123!

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: andreheijstek
  password: Dwrzn123!


